.TH BIP 1 "10 October 2005"

.SH NAME

bipgenconfig \- BIP IRC Proxy configuration program

.SH SYNOPSIS

\fBbipgenconfig\fP

.SH DESCRIPTION

bipgenconfig will help you build a configuration file for BIP IRC Proxy

.SH SEE ALSO

bip, bip.conf, bipmkpw

.SH AUTHOR

Arnaud 'nohar' Cornet
Loïc 'Kyoshiro' Gomez

Thanks to jj, YS and lafouine, for hanging around while we were coding.

Crypto shamelessly taken from Christophe 'sexy' Devine.

